import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/utils/theme/theme";
import { auth } from '@/auth';
import SessionProvider  from '@/context/session_context';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)

{

  const session= await auth()
  console.log(session,'seee')

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <SessionProvider session={session}>

          <ThemeProvider theme={theme}>{children}</ThemeProvider>
          </SessionProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
